# See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "mn/"
    schedule:
      interval: "weekly"
