---
title: "Minnesota Covid 19 data"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

# Introduction

What is the trend in Covid-19 cases in Minnesota?

# `r format(Sys.time(), '%B %e, %Y')`

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(scales)

knitr::opts_chunk$set(
  # Don't put code in the doc
  echo = FALSE,
  # Don't put messages from code in the doc
  message = FALSE,
  # Don't put code warnings in the doc
  warning = FALSE,
  # stop on error instead of continuing
  error = FALSE,
  # Don't let figures float
  # Needs "float" package, see https://stackoverflow.com/a/36234023/34935
  fig.pos = "H",
  # Default height 3.75 inches: two per page plus text
  fig.height = 3.75
)

theme_set(theme_bw() +
            theme(plot.title=element_text(size=25),
                  panel.grid = element_line(colour="grey85")))
```

```{r funcs}
add_rolling_num <- function(df, col, window_days, suffix="_rolling") {
  c_col <- paste0('c_', col)
  df[[c_col]][!is.na(df[[col]])] <- cumsum(df[[col]][!is.na(df[[col]])])
  col1 <- paste0(col, suffix)
  df[[col1]] <- (df[[c_col]] - lag(df[[c_col]], window_days)) / window_days
  df
}

# add_rolling_rate <- function(df, rate, numer, denom, window_days) {
#   df <- add_rolling_num(df, numer, window_days)
#   df <- add_rolling_num(df, denom, window_days)
#   c_numer <- paste0('c_', numer)
#   c_denom <- paste0('c_', denom)
#   df[[rate]] <- (df[[c_numer]] - lag(df[[c_numer]], window_days)) /
#     (df[[c_denom]] - lag(df[[c_denom]], window_days))
#   df
# }

change_in_percent <- function(vec, window_days, round_n=0) {
  stopifnot(length(vec) >= window_days)
  last <- tail(vec, 1)
  last_minus <- head(tail(vec, window_days+1), 1)
  delta <- (last - last_minus)
  fmt <- paste0("%+.", round_n, "f (%+.", round_n, "f%%)")
  sprintf(fmt, delta, 100* delta / last_minus, 1)
}

CHANGE_WINDOW <- 14
ROLLING_WINDOW <- 7
```

```{r graphs, fig.show = "hold", out.width = "50%"}
########## hospitalized

hospdata <- read_tsv('data/hosptable.tsv')
names(hospdata) <- c('date', 'icu_admits', 'all_admits',
                    'total_hosp', 'total_icu_hosp')
hospdata <- hospdata %>% mutate(
  date = as.Date(paste0("2020/", date), format="%Y/%m/%d"),
  # july 4 had "-" in the data
  icu_admits = as.numeric(icu_admits),
  all_admits = as.numeric(all_admits)
)

# Weird data on Oct 3, 2020, where Oct 2 and 3 had a bunch of zeros
# last_day <- hospdata %>% filter(all_admits > 0) %>% pull(date) %>% max(na.rm=T)
last_day <- max(hospdata$date, na.rm=T)

# last 4 weeks
# first_day <- last_day - 28*1
# last 8 weeks
# first_day <- last_day - 28*2
# last 12 weeks
# first_day <- last_day - 28*3
# last 16 weeks
# first_day <- last_day - 28*4
# last 365 days
 first_day <- last_day - 365

# hospdata <- hospdata %>% filter(date <= last_day)

# Controls the amount of smoothing for the default loess smoother.
# Smaller numbers produce wigglier lines, larger numbers produce smoother lines.
# default: 0.75
loess_span <- 0.5

hospdata <- add_rolling_num(hospdata, 'icu_admits', ROLLING_WINDOW)
hospdata <- add_rolling_num(hospdata, 'all_admits', ROLLING_WINDOW)

hospdataf1 <- head(hospdata,-7)

# change in icu_admits_rolling over last CHANGE_WINDOW days
icu_admits_rolling_delta7_percent <- change_in_percent(hospdataf1$icu_admits_rolling, CHANGE_WINDOW)

# change in all_admits_rolling over last CHANGE_WINDOW days
all_admits_rolling_delta7_percent <- change_in_percent(hospdataf1$all_admits_rolling, CHANGE_WINDOW)

hospdata_long <- hospdata %>%
  pivot_longer(c('icu_admits', 'icu_admits_rolling', 'all_admits', 'all_admits_rolling')) %>%
  filter(date >= first_day) %>%
  mutate(color = ifelse(name %in% c('icu_admits', 'icu_admits_rolling'), 'icu_admits', 'all_admits'),
         size = ifelse(name %in% c('icu_admits', 'all_admits'), 0.25, 1)) %>%
  filter(!(name %in% c('icu_admits_rolling', 'all_admits_rolling') & (date > max(hospdataf1$date, na.rm=T))))

ggplot(hospdata_long %>% filter(name %in% c('icu_admits', 'all_admits')),
       aes(date, value, group=name, color=color)) +
  geom_point(alpha=0.25) +
  geom_line(data=hospdata_long %>% filter(name %in% c('icu_admits_rolling', 'all_admits_rolling')),
            aes(size=size, alpha=size)) +
  geom_line(data=hospdata_long %>% filter(name %in% c('icu_admits', 'all_admits')),
            aes(size=size, alpha=size)) +
  labs(title="Hospital admissions",
       subtitle=paste0(
                "icu admits average ", round(tail(hospdata$icu_admits_rolling, 1)),
                ", 14-day change ", icu_admits_rolling_delta7_percent,
                "\nall admits average ",
                round(tail(hospdata$all_admits_rolling, 1)),
                ", 14-day change ", all_admits_rolling_delta7_percent, "\n",
                "Last 7 days may have incomplete data."),
       y="admitted on a given date.") +
  scale_y_continuous(limits=c(0,NA)) +
  scale_size_identity() +
  scale_alpha_identity() +
  scale_x_date(date_minor_breaks="1 month")

rm(hospdata)
rm(hospdata_long)

########## deaths

deathdata <- read_tsv('data/deathtable.tsv')
names(deathdata) <- c('date', 'daily_deaths', 'cumulative_deaths')
deathdata <- deathdata %>%
  mutate(
    date = as.Date(paste0("2020/", date), format="%Y/%m/%d"),
    # july 4 had "-" in the data
    daily_deaths = as.numeric(daily_deaths)
  ) %>%
  add_rolling_num('daily_deaths', ROLLING_WINDOW)

ggplot(deathdata %>% filter(date >= first_day),
       aes(date, daily_deaths)) +
  geom_point(aes(y=daily_deaths), alpha=0.25) +
  geom_line(aes(y=daily_deaths_rolling), size=1) +
  geom_line(aes(y=daily_deaths), alpha=0.25) +
  labs(title="Daily deaths",
       subtitle=paste0(
         "average ", round(tail(deathdata$daily_deaths_rolling, 1)),
         ", 14-day change ",
         change_in_percent(deathdata$daily_deaths_rolling, CHANGE_WINDOW))) +
  scale_y_continuous(limits=c(0,NA)) +
  scale_alpha_identity() +
  scale_x_date(date_minor_breaks="1 month")

########## confirmed cases - last 7 days may be incomplete

casedata <- read_tsv('data/casetable.tsv')
names(casedata) <- c(
  'date',
  'confirmed_cases',
  'cumulative_confirmed_cases',
  'probable_cases',
  'cumulative_probable_cases',
  'cumulative_positive_cases')
casedata <- casedata %>%
  mutate(
    date = as.Date(paste0("2020/", date), format="%Y/%m/%d"),
    positive_cases = cumulative_positive_cases - lag(cumulative_positive_cases)
  ) %>%
  add_rolling_num('positive_cases', ROLLING_WINDOW)

# make alpha of last 7 days less
the_alpha <- 0.1
casedata$alpha <- c(rep(0.25, nrow(casedata)-7), rep(the_alpha, 7))
casedataf <- casedata %>% filter(date >= first_day)
casedataf1 <- head(casedataf,-7)
ggplot(casedataf,
       aes(date, positive_cases)) +
  geom_point(aes(alpha=alpha)) +
  geom_line(aes(alpha=alpha)) +
  geom_line(data=casedataf1, aes(y=positive_cases_rolling), size=1) +
  labs(title="Daily confirmed cases (PCR+antigen)",
       subtitle=paste0(
         "average ", round(tail(casedataf1$positive_cases_rolling, 1)),
         ", 14-day change ",
         change_in_percent(casedataf1$positive_cases_rolling, CHANGE_WINDOW), ".",
         "  Last 7 days may have incomplete data.")) +
  scale_y_continuous(limits=c(0,NA)) +
  scale_alpha_identity() +
  scale_x_date(date_minor_breaks="1 month")


########## tests - last 7 days may be incomplete

labdata <- read_tsv('data/labtable.tsv')
names(labdata) <- c(
  'date',
  'mn_lab_tests_pcr',
  'ext_lab_tests_pcr',
  'cumulative_tests_pcr',
  'ext_lab_tests_antigen',
  'cumulative_tests_antigen',
  'total_cumulative_tests')
labdata <- labdata %>% mutate(
  date = as.Date(paste0("2020/", date), format="%Y/%m/%d"),
  # commas throw things off
  total_cumulative_tests = as.integer(gsub(",", "", total_cumulative_tests)),
  daily_tests = total_cumulative_tests - lag(total_cumulative_tests),
  cumulative_tests_pcr = as.integer(gsub(",", "", total_cumulative_tests)),
  daily_tests_pcr = cumulative_tests_pcr - lag(cumulative_tests_pcr)
) %>%
  add_rolling_num('daily_tests', ROLLING_WINDOW)


# make alpha of last 7 days less
labdata$alpha <- c(rep(0.25, nrow(labdata)-7), rep(the_alpha, 7))
labdataf <- labdata %>% filter(date >= first_day)
labdataf1 <- head(labdataf, -7)
ggplot(labdataf, aes(date, daily_tests)) +
  geom_point(aes(alpha=alpha)) +
  geom_line(data=labdataf, aes(alpha=alpha)) +
  geom_line(data=labdataf1, aes(y=daily_tests_rolling), size=1) +
  labs(title="Daily tests (PCR+antigen)",
       subtitle=paste0(
         "average ", round(tail(labdataf1$daily_tests_rolling, 1)),
         ", 14-day change ",
         change_in_percent(labdataf1$daily_tests_rolling, CHANGE_WINDOW), ".",
         "  Last 7 days may have incomplete data.")) +
  scale_y_continuous(limits=c(0,NA)) +
  scale_alpha_identity() +
  scale_x_date(date_minor_breaks="1 month")

############ positive test rate
caselabdata <- casedata %>% inner_join(labdata, by=c('date')) %>%
  mutate(positive_rate7 = positive_cases_rolling / daily_tests_rolling)
caselabdata$alpha <- c(rep(1, nrow(caselabdata)-7), rep(0.2, 7))

caselabdataf <- head(caselabdata, -7)

ggplot(caselabdata %>% filter(date >= first_day),
       aes(date, positive_rate7)) +
  geom_point(aes(alpha=alpha)) +
  geom_line(aes(alpha=alpha)) +
  labs(title="Positive test rate (unofficial)",
       subtitle=paste0(
         "average ", round(tail(100*caselabdataf$positive_rate7, 1), 1),
         "%, 14-day change ",
         change_in_percent(100*caselabdataf$positive_rate7, CHANGE_WINDOW, 1), ".",
         "  Last 7 days may have incomplete data."),
       y="confirmed cases / tests (rolling 7 days)") +
  scale_y_continuous(limits=c(0,NA), labels=percent) +
  scale_alpha_identity() +
  geom_hline(yintercept=0.05, linetype='dashed') +
  scale_x_date(date_minor_breaks="1 month")

hospcapdata <- read_csv('data/HospitalCapacity_HistoricCSV_tcm1148-449110.csv')
hospcapdata <- hospcapdata %>% rename(
  date=`Data Date (MM/DD/YYYY)`,
  value=Value_NUMBER,
  metric=Metric
)
hospcapdata <- hospcapdata %>% mutate(
  date = as.Date(date, "%m/%d/%Y"),
  metric = gsub("Number of ", "", metric),
  Detail2 = tolower(Detail2),
  metric1 = if_else(metric == "beds",
                    paste(metric, Detail1, coalesce(Detail3, "")),
                    if_else(metric == "patients",
                            paste(metric, Detail1, Detail3),
                            if_else(metric == "ventilators",
                                    paste(metric, Detail2, coalesce(Detail3, ""),
                                          coalesce(Detail4, "")),
                                    "??"
                            ))),
  metric1 = gsub("\\+", "", metric1),
  metric1 = gsub(" +$", "", metric1)
) %>%
  arrange(date)

# ggplot(hospcapdata, aes(date, value, group=metric1, color=metric1)) + geom_line()

hospcapdata_wide <- hospcapdata %>%
  pivot_wider(id_cols=date, names_from=metric1, values_from=value)
hospcapdata_wide <- hospcapdata_wide %>%
  mutate(
    icu_bed_capacity_used = (`patients ICU COVID` + `patients ICU non-COVID`) /
      `beds ICU`,
    non_icu_bed_capacity_used = (`patients Non-ICU COVID` + `patients Non-ICU non-COVID`) /
      `beds Non-ICU`,
    ventilator_capacity_used = `ventilators in use` / `ventilators capacity`
  ) %>%
  add_rolling_num('icu_bed_capacity_used', ROLLING_WINDOW) %>%
  add_rolling_num('non_icu_bed_capacity_used', ROLLING_WINDOW) %>%
  add_rolling_num('ventilator_capacity_used', ROLLING_WINDOW)

hospcapdata_used <- hospcapdata_wide %>%
  select(date,
         icu_bed_capacity_used,
         non_icu_bed_capacity_used,
         ventilator_capacity_used,
         icu_bed_capacity_used_rolling,
         non_icu_bed_capacity_used_rolling,
         ventilator_capacity_used_rolling
         ) %>%
  rename_with(~gsub('_capacity_used', '', .x)) %>%
  pivot_longer(cols=!date,
               names_to = "type", values_to="capacity_used")

hospcapdata_maxdate <- max(hospcapdata$date)
hospcapdata_used <- hospcapdata_used %>%
  mutate(
    type = gsub("non_icu_bed", "non-ICU bed", type),
    type = gsub("icu_bed", "ICU bed", type),
    type = gsub("_rolling", " (rolling)", type),
    alpha = if_else(date > (hospcapdata_maxdate - 4), 0.4, 1),
    alpha = if_else(!grepl("rolling", type), 0.35, alpha),
    size = if_else(grepl("rolling", type), 2, 1),
    name = if_else(grepl("ventilator", type), "ventilator",
                    if_else(grepl("non-ICU bed", type), "non-ICU bed",
                            if_else(grepl("ICU bed", type), "ICU bed",
                                    "??"))))

hospcapdata_wide_m4 <- head(hospcapdata_wide,-4)

# change in icu_bed_capacity_used_rolling over last CHANGE_WINDOW days
icu_bed_capacity_delta_percent <- change_in_percent(100*hospcapdata_wide_m4$icu_bed_capacity_used_rolling, CHANGE_WINDOW)

# change in non_icu_bed_capacity_used_rolling over last CHANGE_WINDOW days
non_icu_bed_capacity_delta_percent <- change_in_percent(100*hospcapdata_wide_m4$non_icu_bed_capacity_used_rolling, CHANGE_WINDOW)

# change in ventilator_capacity_used_rolling over last CHANGE_WINDOW days
ventilator_capacity_delta_percent <- change_in_percent(100*hospcapdata_wide_m4$ventilator_capacity_used_rolling, CHANGE_WINDOW)

ggplot(hospcapdata_used, aes(date, capacity_used,
                             group=type,
                             color=name,
                             alpha=alpha,
                             size=size)) +
  geom_line() +
  geom_point(data=hospcapdata_used %>% filter(!grepl("rolling", type))) +
  scale_y_continuous(limits=c(0, 1), labels=scales::percent) +
  labs(title="Bed and ventilator capacity used",
       subtitle=paste(
         "Not including surge capacity.  Data may change in last 4 days.",
         paste0("icu bed capacity used average ",
                round(tail(100*hospcapdata_wide_m4$icu_bed_capacity_used_rolling, 1)),
                "%, 14-day change ", icu_bed_capacity_delta_percent),
         paste0("non-icu bed capacity used average ",
                round(tail(100*hospcapdata_wide_m4$non_icu_bed_capacity_used_rolling, 1)),
                "%, 14-day change ", non_icu_bed_capacity_delta_percent),
         paste0("ventilator capacity used average ",
                round(tail(100*hospcapdata_wide_m4$ventilator_capacity_used_rolling, 1)),
                "%, 14-day change ", ventilator_capacity_delta_percent),
         sep="\n"),
       y="% capacity used") +
  scale_alpha_identity() +
  scale_size_identity()

# Older, simpler graph:
if (FALSE) {
  ggplot(hospcapdata_used %>% filter(!grepl("rolling", type)),
         aes(date, capacity_used,
             group=type,
             color=name,
             alpha=if_else(date > (hospcapdata_maxdate-4), 0.35, 1))) +
    geom_line() +
    geom_point() +
    scale_y_continuous(limits=c(0, 1), labels=scales::percent) +
    labs(title="Bed and ventilator capacity used",
         subtitle="Not including surge capacity.  Data may change in last 4 days.",
         y="% capacity used") +
    scale_alpha_identity() +
    scale_size_identity()
}
```

Data from https://www.health.state.mn.us/diseases/coronavirus/situation.html
and https://mn.gov/covid19/data/response-prep/response-capacity.jsp.

Capacity csv is at https://mn.gov/covid19/assets/HospitalCapacity_HistoricCSV_tcm1148-449110.csv.